### ISSUE TITLE
バグ　admin/order/show

### ISSUE THREAD

**Issue by hojokaban** [one-short-rib/nagano-cake-ec#43]
8行目:
  @order.member.name
　 memberにnameカラムはありません！

**Comment by mtzkhrh** [comment]
担当ははねちゃんかな？
これに関してはfeature-headerのブランチで、
application_helperでfull_nameメソッドを作ったので、
マージした後、編集時に参照してください。

**Comment by hojokaban** [comment]
そうなんですね！
僕も使います！！
