### ISSUE TITLE
adminページでのheaderの表示

### ISSUE THREAD

**Issue by hojokaban** [one-short-rib/nagano-cake-ec#82]
adminがログアウト状態の時のヘッダーの表示がどうあるべきか。

現状は
商品一覧、会員の新規登録、会員のログイン、
へのリンクが表示されている

**Comment by mtzkhrh** [comment]
adminのワイヤーフレーム、ログインページのヘッダーで確認してください。
現状のそれがワイヤーフレームと同じなので問題無し。

**Comment by hojokaban** [comment]
おけです！
