### ISSUE TITLE
パスワード変更画面の遷移

### ISSUE THREAD

**Issue by hojokaban** [one-short-rib/nagano-cake-ec#87]

**Comment by mtzkhrh** [comment]
今回の要件定義の中にないので作ってないです。
余裕があれば手を出す感じで

**Comment by hojokaban** [comment]
UIフローにあったのでやらないといけないと思っていました！
了解です！

**Comment by mtzkhrh** [comment]
UIフローは見落としてた。
今画面遷移だけでも作ろうとしたけどなぜかrootにリダイレクトされる。
